set_property PACKAGE_PIN K15 [get_ports {ext_dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_dout[1]}]
set_property PACKAGE_PIN J15 [get_ports {ext_din[0]}]
set_property PACKAGE_PIN L16 [get_ports {ext_din[1]}]
set_property PACKAGE_PIN M13 [get_ports {ext_addr[0]}]
set_property PACKAGE_PIN R15 [get_ports {ext_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_addr[1]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN R17 [get_ports ext_wr]
set_property IOSTANDARD LVCMOS33 [get_ports ext_wr]
set_property PACKAGE_PIN C12 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]


set_property PACKAGE_PIN H17 [get_ports {ext_dout[0]}]
